//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreApplicationDALayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTickets_TicketsSold
    {
        public int id { get; set; }
        public string eventname { get; set; }
        public Nullable<System.DateTime> eventDate { get; set; }
        public Nullable<int> groupId { get; set; }
        public Nullable<int> ticketId { get; set; }
        public string custtype { get; set; }
        public string ticketType { get; set; }
    }
}
