//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreApplicationDALayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events_Customergroup
    {
        public int id { get; set; }
        public string eventName { get; set; }
        public string groupName { get; set; }
        public Nullable<int> groupId { get; set; }
        public Nullable<int> ticketId { get; set; }
    }
}
